feat: accept tenant id passed as superadmin for agency create
Onlineberatung/onlineBeratung-agencyService pull request #180
Opened 2023-09-06 21:45 UTC by tkuzynow

Fixes #

## Proposed Changes

  -
  -
  -

2023-09-06 21:45 UTC, vi-sudo commented
Task linked: [OB-5391 Adapt the agency create endpoint the accept a tenant id](https://app.clickup.com/t/6656196/OB-5391)

2023-09-07 08:13 UTC, SheepFromHeaven requested changes

2023-09-07 08:13 UTC, SheepFromHeaven commented on src/main/resources/application-local.properties
> +spring.liquibase.password=YwIfv8A2RkNbMrib1
should this be in here?

2023-09-07 12:18 UTC, tkuzynow commented on src/main/resources/application-local.properties
> +spring.liquibase.password=YwIfv8A2RkNbMrib1
no. Reverted and changed password and updated secrets.

2023-09-12 17:41 UTC, SheepFromHeaven approved these changes

2023-09-13 07:58 UTC, merged